{
 "title": "Metales Valiosos",
 "time": { "from": "2026-01-14T11:43:17.914Z", "to": "2026-01-14T11:45:21.036Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "unidad_peso", "label": "Unidad de Peso", "query": "Onzas : 1, Gramos : 31.1034768" },
   { "name": "tasa_cambio", "label": "Moneda", "query": " $ : 1,  € : 0.92" }
  ]
 },
 "panels": [
  {
   "title": "Oro (Actual) ${tasa_cambio:text}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Oro Actual",
     "measurement": "metals",
     "query": "SELECT last(\"price\") / $unidad_peso * $tasa_cambio FROM \"metals\" WHERE \"metal\" = 'XAU'"
    }
   ]
  },
  {
   "title": "Plata (Actual) ${tasa_cambio:text}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Plata Actual",
     "measurement": "metals",
     "query": "SELECT last(\"price\") / $unidad_peso * $tasa_cambio FROM \"metals\" WHERE \"metal\" = 'XAG'"
    }
   ]
  },
  {
   "title": "Platino (Actual) ${tasa_cambio:text}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Platino Actual",
     "measurement": "metals",
     "query": "SELECT last(\"price\") / $unidad_peso * $tasa_cambio FROM \"metals\" WHERE \"metal\" = 'XPT'"
    }
   ]
  },
  {
   "title": "Bronce (Actual) ${tasa_cambio:text}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Bronce Actual",
     "measurement": "metals",
     "query": "SELECT last(\"price\") / $unidad_peso * $tasa_cambio FROM \"metals\" WHERE \"metal\" = 'HG'"
    }
   ]
  },
  {
   "title": "Comparación de precios",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Oro ${tasa_cambio:text}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "metals",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / $unidad_peso * $tasa_cambio" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "metal::tag", "operator": "=", "value": "XAU" }
     ]
    },
    {
     "alias": "Plata ${tasa_cambio:text}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "metals",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / $unidad_peso * $tasa_cambio" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "metal::tag", "operator": "=", "value": "XAG" }
     ]
    },
    {
     "alias": "Platino ${tasa_cambio:text}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "metals",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / $unidad_peso * $tasa_cambio" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "metal::tag", "operator": "=", "value": "XPT" }
     ]
    },
    {
     "alias": "Bronce ${tasa_cambio:text}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "metals",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / $unidad_peso * $tasa_cambio" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "metal::tag", "operator": "=", "value": "HG" }
     ]
    }
   ]
  },
  {
   "title": "Precio mínimo y máximo del oro (${tasa_cambio:text})",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Precio Mínimo",
     "measurement": "metals",
     "query": "SELECT MIN(\"price\") / $unidad_peso * $tasa_cambio FROM metals WHERE \"metal\"='XAU'\n",
     "select": [
      [
       { "params": [ "price" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metal::tag", "operator": "=", "value": "XAU" }
     ]
    },
    {
     "alias": "Precio Máximo",
     "query": "SELECT MAX(\"price\") / $unidad_peso * $tasa_cambio FROM metals WHERE \"metal\"='XAU'"
    }
   ]
  },
  {
   "title": "Precio del oro",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Oro ${tasa_cambio:text}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "metals",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / $unidad_peso * $tasa_cambio" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "metal::tag", "operator": "=", "value": "XAU" }
     ]
    }
   ]
  },
  {
   "title": "Precio del platino",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Platino ${tasa_cambio:text}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "metals",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / $unidad_peso * $tasa_cambio" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "metal::tag", "operator": "=", "value": "XPT" }
     ]
    }
   ]
  },
  {
   "title": "Precio de la plata",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Plata ${tasa_cambio:text}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "metals",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / $unidad_peso * $tasa_cambio" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "metal::tag", "operator": "=", "value": "XAG" }
     ]
    }
   ]
  },
  {
   "title": "Precio del bronce",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Bronce ${tasa_cambio:text}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "metals",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / $unidad_peso * $tasa_cambio" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "metal::tag", "operator": "=", "value": "HG" }
     ]
    }
   ]
  },
  {
   "title": "Ratio Oro / Plata (Gold-Silver Ratio)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Últimas Cotizaciones (Tabla)",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_metal",
     "groupBy": [
      { "params": [ "metal" ], "type": "tag" }
     ],
     "measurement": "metals",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / $unidad_peso * $tasa_cambio" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}